# development
server:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 4000
  port:
  timezone: UTC
  cluster:  false
  base_url: http://127.0.0.1:4000/

db:
  db: coke_redis-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

redis:
  # optional, default: null
  password:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 6379
  port:

cookie:
  secret: kimjkCFGyblDTk09cga93313dc222b098ujmnhFQ

session:
  # optional, default: sessions
  collection:

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:
  - redis

# libs that must run after server started
started:

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:
  secret:
  s3:
    bucket: assets.dev.coke_redis

