# development
server:
  host: 127.0.0.1
  port: 4000
  timezone: 'UTC'
  cluster: false

db:
  db: coke_redis-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

redis:
  # optional, default: null
  password:
  # optional, default: 127.0.0.1
  host:
  # optional, default: 6379
  port:

session:
  # optional, default: sessions
  collection:
  secret: 2e798a6d81f7235c10a93313dc222b5763a62ba6

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:
  - redis

# libs that must run after server started
started: []


